# permissions for end users to edit orders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: order-editor-role
rules:
- apiGroups:
  - webapp.order.io
  resources:
  - orders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.order.io
  resources:
  - orders/status
  verbs:
  - get
